### PR TITLE
Test Fix

### PR DESCRIPTION
**Pull request by Lukeghenco**
This test was broken. The ES6 variables are required to be wrapped in (function(){"use strict";})();. @peterbell

### CODE REVIEW

**Comment by PeterBell** [comment]
Could @mendelB or @aturkewi just give eyes on this and a 👍 if it looks good?

**Comment by AnnJohn** [comment]
also assigning to @pletcher just in case

**Comment by mendelB** [comment]
@Lukeghenco I think the issue here may have been with the node version. I ran the tests in master with an older version of node and got the  `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` error and then using your fix indeed completely fixed it. But upon upgrading node to latest stable version I was able to pass the old test in master
cc: @PeterBell @aturkewi @pletcher

**Comment by Lukeghenco** [comment]
@mendelB Yes, this error does go away if you have node v.6 installed. I currently use 5.1, and it is the version that Learn has us install in the extra curriculum Node track as well. It might be better to have it wrapped in this function until everyone fully jumps onto the v.6 bandwagon. It is still a pretty new version of Node. I have ran into a few students that have had an issue with this lab, because of these errors.

cc: @PeterBell @aturkewi @pletcher

**Comment by mendelB** [comment]
@Lukeghenco Ahh I see what you mean. in that case this would be a great fix 👍  
(I guess it's a question of whether we should cater to old node versions, or have everyone upgrade at this point which using `n` _should_ be mad easy but I guess could lead to tons of specific env issues...)
I'll defer on this one to the great @pletcher

**Comment by aturkewi** [comment]
I think all of the new JS curriculum is written for ES6 and at learn.co/manual_setup we instruct students to get `n latest`.

I think we may want to actually update the node curriculum to have students do the same there rather than try and change a bunch of tests to work with an old version ofJS. 

@Lukeghenco where in the Node curriculum does it instruct students to use v.5?

**Comment by Lukeghenco** [comment]
@aturkewi 

Haha just found the lesson and it has been updated since I finished it up a couple weeks ago. https://learn.co/tracks/introduction-to-node-js/intro-to-node-js/node-basics/installing-node-and-npm. On July 8th, it was changed to 6.3. Maybe a better fix is to add more notifications for students to install a newer version of Node. JS is scary to most of our students. They are leaving the comfortable world of Ruby to the wild west of JS development. 

@PeterBell @mendelB @pletcher

**Comment by aturkewi** [comment]
Looks like this one is all set. Closing PR

@Lukeghenco if I've misunderstood that somehow though, please feel free to re-open the PR :)

**Pull request closed without merging**
